#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
limit = 4000000
fibon = [1, 2, 3, 5, 8, 13, 21, 34, 55, 89]
i = len(fibon)-1
while fibon[i] <= limit:
    fibon.append(fibon[i] + fibon[i-1])
    i = i+ 1
total = 0
for item in fibon:
    if item % 2 == 0:
        total += item

print total
#4613732